[build]
dockerfile = "./Dockerfile"

[deploy]
startCommand = "poetry run python main.py"   # use the venv!
restartPolicyType = "on_failure"

# Persist SQLite + APScheduler jobstore
[volumes]
[volumes.data]
mountPath = "/app/data"
