[build]
dockerfile = "./Dockerfile"

[deploy]
startCommand = "python main.py"
restartPolicyType = "on_failure"

# Persist SQLite + APScheduler jobstore
[volumes]
[volumes.data]
mountPath = "/app/data"
